import type { AnalyzeStoryOutput } from '@/ai/flows/analyze-story';
import type { GenerateStoryboardOutput, GenerateScenesOutput as AIJenGenerateScenesOutput } from '@/ai/flows/generate-storyboard'; // Assuming generateStoryboardOutput contains scene structure

export type StoryAnalysis = AnalyzeStoryOutput;

// This Scene type will be used for both storyboard and generated scenes.
// For storyboard scenes from generateStoryboard, imageUrl might be imageUri.
// For generated scenes from generateScenes, imageUrl will be the direct image URL.
export interface Scene {
  sceneDescription: string;
  imageUrl?: string; // This can hold data URI from storyboard or URL from scene generation
  // Optional: if you need to distinguish storyboard prompts/images from final scene images
  storyboardImageUri?: string; 
  promptForSceneGeneration?: string; 
}

export type GenerateScenesOutput = AIJenGenerateScenesOutput; // Assuming this is an array of scenes from AI.

export interface Project {
  id: string;
  title: string;
  storyText: string;
  analysis?: StoryAnalysis;
  storyboard?: GenerateStoryboardOutput; // Array of scenes with descriptions and image URIs
  visualStyle?: string; // ID of the selected visual style
  generatedScenes?: Scene[]; // Scenes generated by generateScenes AI flow
  videoUrl?: string; // Placeholder for final video URL or path
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
}

export interface VisualStyle {
  id: string;
  name: string;
  description: string;
  previewImageUrl: string;
  dataAiHint: string;
  promptFragment: string; // Fragment to add to AI prompt for this style
}

export const visualStyles: VisualStyle[] = [
  { id: 'cinematic', name: 'Cinematic', description: 'Dramatic lighting, rich colors.', previewImageUrl: 'https://placehold.co/150x100.png', dataAiHint: 'movie film', promptFragment: 'cinematic style, dramatic lighting, high contrast, rich colors' },
  { id: 'anime', name: 'Anime', description: 'Classic Japanese animation style.', previewImageUrl: 'https://placehold.co/150x100.png', dataAiHint: 'anime art', promptFragment: 'anime style, vibrant colors, expressive characters, detailed backgrounds' },
  { id: 'pixelart', name: 'Pixel Art', description: 'Retro 8-bit or 16-bit style.', previewImageUrl: 'https://placehold.co/150x100.png', dataAiHint: 'pixel video-game', promptFragment: 'pixel art style, 8-bit, retro gaming aesthetic' },
  { id: 'watercolor', name: 'Watercolor', description: 'Soft, flowing, artistic.', previewImageUrl: 'https://placehold.co/150x100.png', dataAiHint: 'watercolor painting', promptFragment: 'watercolor painting style, soft edges, flowing colors, artistic' },
  { id: 'noir', name: 'Film Noir', description: 'Black and white, high contrast, shadows.', previewImageUrl: 'https://placehold.co/150x100.png', dataAiHint: 'noir film', promptFragment: 'film noir style, black and white, high contrast, dramatic shadows, mysterious atmosphere' },
];
